main: me.bluecoaster455.worldspawn.WorldSpawn
author: Bluecoaster455
version: 1.5
name: WorldSpawn
commands:
  spawn:
  setspawn:
  sethub:
  hub:
  linkspawn:
  delspawn:
  worldspawn:
  spawnonrespawn: